from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Table,
    TableStyle
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from datetime import datetime
import os


def generate_bulk_pdf_report(
        filename,
        total_modules,
        healthy_count,
        defective_count,
        avg_risk,
        highest_module,
        highest_risk,
        top_risk_modules):

    os.makedirs("reports", exist_ok=True)

    pdf_path = "reports/IntelliCode_Bulk_Report.pdf"

    doc = SimpleDocTemplate(pdf_path)

    styles = getSampleStyleSheet()

    story = []

    # ----------------------------------------------------
    # Title
    # ----------------------------------------------------

    story.append(
        Paragraph(
            "<font size=22><b>IntelliCode</b></font>",
            styles["Title"]
        )
    )

    story.append(
        Paragraph(
            "<b>AI-Powered Bulk Software Defect Prediction Report</b>",
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(
            f"Generated on: {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"Dataset: <b>{filename}</b>",
            styles["Normal"]
        )
    )

    story.append(Paragraph("<br/>", styles["Normal"]))

    # ----------------------------------------------------
    # Summary
    # ----------------------------------------------------

    story.append(
        Paragraph("<b>Prediction Summary</b>", styles["Heading1"])
    )

    summary = [
        ["Metric", "Value"],
        ["Total Modules", str(total_modules)],
        ["Healthy Modules", str(healthy_count)],
        ["Defective Modules", str(defective_count)],
        ["Average Risk Score", f"{avg_risk}%"],
        ["Highest Risk Module", f"Module {highest_module}"],
        ["Highest Risk Score", f"{highest_risk}%"]
    ]

    table = Table(summary, colWidths=[3*inch, 2.5*inch])

    table.setStyle(TableStyle([
        ("BACKGROUND",(0,0),(-1,0),colors.darkblue),
        ("TEXTCOLOR",(0,0),(-1,0),colors.white),
        ("GRID",(0,0),(-1,-1),1,colors.grey),
        ("BACKGROUND",(0,1),(-1,-1),colors.beige),
        ("BOTTOMPADDING",(0,0),(-1,0),10),
        ("ALIGN",(0,0),(-1,-1),"CENTER")
    ]))

    story.append(table)

    story.append(Paragraph("<br/>", styles["Normal"]))

    # ----------------------------------------------------
    # Top Risk Modules
    # ----------------------------------------------------

    story.append(
        Paragraph(
            "<b>Top 10 High-Risk Modules</b>",
            styles["Heading1"]
        )
    )

    data = [["Module", "Risk Score", "Prediction"]]

    for module in top_risk_modules:

        data.append([
            str(module["Module ID"]),
            f'{module["Risk Score"]}%',
            module["Prediction"]
        ])

    risk_table = Table(data)

    risk_table.setStyle(TableStyle([
        ("BACKGROUND",(0,0),(-1,0),colors.red),
        ("TEXTCOLOR",(0,0),(-1,0),colors.white),
        ("GRID",(0,0),(-1,-1),1,colors.black),
        ("BACKGROUND",(0,1),(-1,-1),colors.whitesmoke),
        ("ALIGN",(0,0),(-1,-1),"CENTER")
    ]))

    story.append(risk_table)

    story.append(Paragraph("<br/>", styles["Normal"]))

    # ----------------------------------------------------
    # Recommendations
    # ----------------------------------------------------

    story.append(
        Paragraph(
            "<b>AI Recommendations</b>",
            styles["Heading1"]
        )
    )

    recommendations = """
    • Prioritize testing for high-risk modules.<br/><br/>
    • Perform detailed code reviews on defect-prone modules.<br/><br/>
    • Increase unit test coverage for complex modules.<br/><br/>
    • Refactor highly complex code to improve maintainability.<br/><br/>
    • Re-analyze the software after implementing improvements.
    """

    story.append(
        Paragraph(recommendations, styles["Normal"])
    )

    story.append(Paragraph("<br/>", styles["Normal"]))

    # ----------------------------------------------------
    # Footer
    # ----------------------------------------------------

    story.append(
        Paragraph(
            "<b>Generated by IntelliCode</b>",
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(
            "AI-Powered Software Defect Prediction Platform",
            styles["Normal"]
        )
    )

    doc.build(story)

    return pdf_path