from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
import os
from datetime import datetime


def generate_pdf_report(
    filename,
    prediction,
    risk_score,
    risk_level,
    loc,
    complexity,
    mi
):
    os.makedirs("reports", exist_ok=True)

    pdf_path = os.path.join(
        "reports",
        "IntelliCode_Report.pdf"
    )

    doc = SimpleDocTemplate(pdf_path)

    styles = getSampleStyleSheet()

    story = []

    story.append(
        Paragraph("<b><font size=18>IntelliCode AI Report</font></b>", styles["Title"])
    )

    story.append(
        Paragraph(
            f"Generated: {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}",
            styles["Normal"]
        )
    )

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(
        Paragraph("<b>Prediction Summary</b>", styles["Heading2"])
    )

    story.append(Paragraph(f"File Name : {filename}", styles["Normal"]))
    story.append(Paragraph(f"Prediction : {prediction}", styles["Normal"]))
    story.append(Paragraph(f"Risk Score : {risk_score}%", styles["Normal"]))
    story.append(Paragraph(f"Risk Level : {risk_level}", styles["Normal"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(
        Paragraph("<b>Software Metrics</b>", styles["Heading2"])
    )

    story.append(Paragraph(f"LOC : {loc}", styles["Normal"]))
    story.append(Paragraph(f"Cyclomatic Complexity : {complexity}", styles["Normal"]))
    story.append(Paragraph(f"Maintainability Index : {mi}", styles["Normal"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(
        Paragraph("<b>Overall Assessment</b>", styles["Heading2"])
    )

    if risk_score >= 70:

        assessment = (
            "This module has a HIGH probability of defects. "
            "Additional testing and code review are strongly recommended."
        )

    elif risk_score >= 40:

        assessment = (
            "This module has a MODERATE risk level. "
            "Focused testing is recommended."
        )

    else:

        assessment = (
            "This module appears healthy with a LOW defect probability."
        )

    story.append(
        Paragraph(assessment, styles["BodyText"])
    )

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(
        Paragraph(
            "<b>Generated by IntelliCode</b>",
            styles["Heading3"]
        )
    )

    doc.build(story)

    return pdf_path