from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime
import os


def generate_pdf_report(
        filename,
        prediction,
        risk_score,
        risk_level,
        loc,
        complexity,
        mi=None):

    os.makedirs("reports", exist_ok=True)

    pdf_path = "reports/IntelliCode_Report.pdf"

    doc = SimpleDocTemplate(pdf_path)

    styles = getSampleStyleSheet()

    story = []

    story.append(
        Paragraph("<b><font size=22>IntelliCode AI Report</font></b>",
                  styles["Title"])
    )

    story.append(
        Paragraph(
            f"Generated : {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}",
            styles["Normal"]
        )
    )

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(
        Paragraph("<b>Prediction Summary</b>",
                  styles["Heading1"])
    )

    story.append(Paragraph(f"<b>File :</b> {filename}", styles["Normal"]))
    story.append(Paragraph(f"<b>Prediction :</b> {prediction}", styles["Normal"]))
    story.append(Paragraph(f"<b>Risk Score :</b> {risk_score}%", styles["Normal"]))
    story.append(Paragraph(f"<b>Risk Level :</b> {risk_level}", styles["Normal"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(
        Paragraph("<b>Software Metrics</b>",
                  styles["Heading1"])
    )

    story.append(Paragraph(f"LOC : {loc}", styles["Normal"]))
    story.append(Paragraph(f"Cyclomatic Complexity : {complexity}", styles["Normal"]))
    story.append(Paragraph(f"Maintainability Index : {mi}", styles["Normal"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(
        Paragraph("<b>AI Assessment</b>",
                  styles["Heading1"])
    )

    if risk_score >= 70:

        assessment = """
        This software module is highly defect-prone.
        Immediate code review, refactoring,
        and additional testing are strongly recommended.
        """

    elif risk_score >= 40:

        assessment = """
        This module has a moderate defect probability.
        Additional testing and code review are recommended.
        """

    else:

        assessment = """
        This module appears healthy with low defect probability.
        Standard testing should be sufficient.
        """

    story.append(
        Paragraph(assessment,
                  styles["Normal"])
    )

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(
        Paragraph("<b>Generated by IntelliCode</b>",
                  styles["Heading2"])
    )

    doc.build(story)

    return pdf_path